//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SkillsEngine
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Skill training.
    /// </summary>
    // *** Start programmer edit section *** (SkillTraining CustomAttributes)

    // *** End programmer edit section *** (SkillTraining CustomAttributes)
    [AutoAltered()]
    [Caption("Skill training")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SkillTrainingE", new string[] {
            "Name as \'Name\'",
            "Url as \'Url\'"})]
    public class SkillTraining : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fUrl;
        
        private IIS.SkillsEngine.Skill fSkill;
        
        // *** Start programmer edit section *** (SkillTraining CustomMembers)

        // *** End programmer edit section *** (SkillTraining CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (SkillTraining.Name CustomAttributes)

        // *** End programmer edit section *** (SkillTraining.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (SkillTraining.Name Get start)

                // *** End programmer edit section *** (SkillTraining.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (SkillTraining.Name Get end)

                // *** End programmer edit section *** (SkillTraining.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SkillTraining.Name Set start)

                // *** End programmer edit section *** (SkillTraining.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (SkillTraining.Name Set end)

                // *** End programmer edit section *** (SkillTraining.Name Set end)
            }
        }
        
        /// <summary>
        /// Url.
        /// </summary>
        // *** Start programmer edit section *** (SkillTraining.Url CustomAttributes)

        // *** End programmer edit section *** (SkillTraining.Url CustomAttributes)
        [StrLen(255)]
        public virtual string Url
        {
            get
            {
                // *** Start programmer edit section *** (SkillTraining.Url Get start)

                // *** End programmer edit section *** (SkillTraining.Url Get start)
                string result = this.fUrl;
                // *** Start programmer edit section *** (SkillTraining.Url Get end)

                // *** End programmer edit section *** (SkillTraining.Url Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SkillTraining.Url Set start)

                // *** End programmer edit section *** (SkillTraining.Url Set start)
                this.fUrl = value;
                // *** Start programmer edit section *** (SkillTraining.Url Set end)

                // *** End programmer edit section *** (SkillTraining.Url Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.SkillsEngine.Skill.
        /// </summary>
        // *** Start programmer edit section *** (SkillTraining.Skill CustomAttributes)

        // *** End programmer edit section *** (SkillTraining.Skill CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.SkillsEngine.Skill Skill
        {
            get
            {
                // *** Start programmer edit section *** (SkillTraining.Skill Get start)

                // *** End programmer edit section *** (SkillTraining.Skill Get start)
                IIS.SkillsEngine.Skill result = this.fSkill;
                // *** Start programmer edit section *** (SkillTraining.Skill Get end)

                // *** End programmer edit section *** (SkillTraining.Skill Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (SkillTraining.Skill Set start)

                // *** End programmer edit section *** (SkillTraining.Skill Set start)
                this.fSkill = value;
                // *** Start programmer edit section *** (SkillTraining.Skill Set end)

                // *** End programmer edit section *** (SkillTraining.Skill Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SkillTrainingE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SkillTrainingE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SkillTrainingE", typeof(IIS.SkillsEngine.SkillTraining));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of SkillTraining.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfSkillTraining CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfSkillTraining CustomAttributes)
    public class DetailArrayOfSkillTraining : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.SkillsEngine.DetailArrayOfSkillTraining members)

        // *** End programmer edit section *** (IIS.SkillsEngine.DetailArrayOfSkillTraining members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type SkillTraining by index.
        /// </summary>
        /// <summary>
        /// Adds object with type SkillTraining.
        /// </summary>
        public DetailArrayOfSkillTraining(IIS.SkillsEngine.Skill fSkill) : 
                base(typeof(SkillTraining), ((ICSSoft.STORMNET.DataObject)(fSkill)))
        {
        }
        
        public IIS.SkillsEngine.SkillTraining this[int index]
        {
            get
            {
                return ((IIS.SkillsEngine.SkillTraining)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.SkillsEngine.SkillTraining dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
