//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.SkillsEngine
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Skill.
    /// </summary>
    // *** Start programmer edit section *** (Skill CustomAttributes)

    // *** End programmer edit section *** (Skill CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("SkillE", new string[] {
            "Name as \'Name\'",
            "Description as \'Description\'",
            "ParentSkill as \'Parent skill\'",
            "ParentSkill.Name as \'Name\'"})]
    [AssociatedDetailViewAttribute("SkillE", "EducationalMaterials", "SkillTrainingE", true, "", "Educational materials", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("SkillE", "ParentSkill", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("SkillL", new string[] {
            "Name as \'Name\'",
            "Description as \'Description\'",
            "ParentSkill as \'Name\'"}, Hidden=new string[] {
            "ParentSkill"})]
    public class Skill : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private string fDescription;
        
        private IIS.SkillsEngine.Skill fParentSkill;
        
        private IIS.SkillsEngine.DetailArrayOfSkillTraining fEducationalMaterials;
        
        // *** Start programmer edit section *** (Skill CustomMembers)

        // *** End programmer edit section *** (Skill CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Skill.Name CustomAttributes)

        // *** End programmer edit section *** (Skill.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Skill.Name Get start)

                // *** End programmer edit section *** (Skill.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Skill.Name Get end)

                // *** End programmer edit section *** (Skill.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Skill.Name Set start)

                // *** End programmer edit section *** (Skill.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Skill.Name Set end)

                // *** End programmer edit section *** (Skill.Name Set end)
            }
        }
        
        /// <summary>
        /// Description.
        /// </summary>
        // *** Start programmer edit section *** (Skill.Description CustomAttributes)

        // *** End programmer edit section *** (Skill.Description CustomAttributes)
        [StrLen(255)]
        public virtual string Description
        {
            get
            {
                // *** Start programmer edit section *** (Skill.Description Get start)

                // *** End programmer edit section *** (Skill.Description Get start)
                string result = this.fDescription;
                // *** Start programmer edit section *** (Skill.Description Get end)

                // *** End programmer edit section *** (Skill.Description Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Skill.Description Set start)

                // *** End programmer edit section *** (Skill.Description Set start)
                this.fDescription = value;
                // *** Start programmer edit section *** (Skill.Description Set end)

                // *** End programmer edit section *** (Skill.Description Set end)
            }
        }
        
        /// <summary>
        /// Skill.
        /// </summary>
        // *** Start programmer edit section *** (Skill.ParentSkill CustomAttributes)

        // *** End programmer edit section *** (Skill.ParentSkill CustomAttributes)
        public virtual IIS.SkillsEngine.Skill ParentSkill
        {
            get
            {
                // *** Start programmer edit section *** (Skill.ParentSkill Get start)

                // *** End programmer edit section *** (Skill.ParentSkill Get start)
                IIS.SkillsEngine.Skill result = this.fParentSkill;
                // *** Start programmer edit section *** (Skill.ParentSkill Get end)

                // *** End programmer edit section *** (Skill.ParentSkill Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Skill.ParentSkill Set start)

                // *** End programmer edit section *** (Skill.ParentSkill Set start)
                this.fParentSkill = value;
                // *** Start programmer edit section *** (Skill.ParentSkill Set end)

                // *** End programmer edit section *** (Skill.ParentSkill Set end)
            }
        }
        
        /// <summary>
        /// Skill.
        /// </summary>
        // *** Start programmer edit section *** (Skill.EducationalMaterials CustomAttributes)

        // *** End programmer edit section *** (Skill.EducationalMaterials CustomAttributes)
        public virtual IIS.SkillsEngine.DetailArrayOfSkillTraining EducationalMaterials
        {
            get
            {
                // *** Start programmer edit section *** (Skill.EducationalMaterials Get start)

                // *** End programmer edit section *** (Skill.EducationalMaterials Get start)
                if ((this.fEducationalMaterials == null))
                {
                    this.fEducationalMaterials = new IIS.SkillsEngine.DetailArrayOfSkillTraining(this);
                }
                IIS.SkillsEngine.DetailArrayOfSkillTraining result = this.fEducationalMaterials;
                // *** Start programmer edit section *** (Skill.EducationalMaterials Get end)

                // *** End programmer edit section *** (Skill.EducationalMaterials Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Skill.EducationalMaterials Set start)

                // *** End programmer edit section *** (Skill.EducationalMaterials Set start)
                this.fEducationalMaterials = value;
                // *** Start programmer edit section *** (Skill.EducationalMaterials Set end)

                // *** End programmer edit section *** (Skill.EducationalMaterials Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "SkillE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SkillE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SkillE", typeof(IIS.SkillsEngine.Skill));
                }
            }
            
            /// <summary>
            /// "SkillL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View SkillL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("SkillL", typeof(IIS.SkillsEngine.Skill));
                }
            }
        }
    }
}
